# SPDX-FileCopyrightText: 2026 The Gatepost authors
# SPDX-License-Identifier: Apache-2.0
"""The kind and the language of a file, which decide the rules that apply to it."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Literal

from check_tells.text import split_lines

# Code and config files get the strict rules. The other kinds can use any script, so they get
# only the emoji check: prose (Markdown), catalogue (translations), exempt (lockfiles, data and
# images) and other (a file type that no rule names).
Kind = Literal["code", "config", "prose", "catalogue", "exempt", "other"]

CODE_EXTENSIONS = frozenset(
    {
        ".ts",
        ".tsx",
        ".mts",
        ".cts",
        ".js",
        ".jsx",
        ".mjs",
        ".cjs",
        ".php",
        ".py",
        ".go",
        ".kt",
        ".kts",
        ".java",
        ".cs",
        ".dart",
        ".swift",
        ".sql",
        ".sh",
        ".bash",
        ".css",
        ".scss",
        ".html",
        ".astro",
        ".vue",
        ".svelte",
    }
)
CONFIG_EXTENSIONS = frozenset(
    {
        ".json",
        ".yml",
        ".yaml",
        ".toml",
        ".xml",
        ".ini",
        ".cfg",
        ".properties",
        ".gradle",
        ".neon",
        ".json5",
        ".jsonc",
    }
)
CONFIG_NAMES = frozenset(
    {"Makefile", "Dockerfile", ".editorconfig", ".gitignore", ".gitattributes", ".npmrc"}
)
PROSE_EXTENSIONS = frozenset({".md", ".mdx"})
EXEMPT_EXTENSIONS = frozenset(
    {".svg", ".lock", ".csv", ".txt", ".api", ".snap", ".png", ".jpg", ".ico"}
)
# A lockfile with the suffix .lock is exempt through EXEMPT_EXTENSIONS, so this names the others.
LOCKFILES = frozenset(
    {
        "pnpm-lock.yaml",
        "package-lock.json",
        "go.sum",
        "Package.resolved",
        "gradle.lockfile",
        "packages.lock.json",
    }
)
CATALOGUE_FOLDERS = frozenset({"locales", "i18n", "l10n", "messages"})
DATA_FOLDERS = frozenset({"data", "vectors"})
CATALOGUE_EXTENSIONS = frozenset({".arb", ".po", ".xlf", ".xliff", ".strings", ".stringsdict"})

LANGUAGE_BY_EXTENSION = {
    ".ts": "javascript",
    ".tsx": "javascript",
    ".mts": "javascript",
    ".cts": "javascript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".astro": "javascript",
    ".vue": "javascript",
    ".svelte": "javascript",
    ".php": "php",
    ".py": "python",
    ".go": "go",
    ".kt": "jvm",
    ".kts": "jvm",
    ".java": "jvm",
    ".cs": "dotnet",
    ".dart": "dart",
    ".swift": "swift",
}
LANGUAGE_BY_INTERPRETER = {"python3": "python", "python": "python", "node": "javascript"}

GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "<auto-generated", "GENERATED CODE")
TEST_PATH = re.compile(
    r"(^|/)(test|tests|__tests__|testdata|Tests)/"
    r"|_test\.(go|dart)$"
    r"|\.(test|spec)\.[cm]?[jt]sx?$"
    r"|(^|/)test_[^/]*\.py$"
    r"|Tests?\.(kt|java|cs|swift)$"
)


@dataclass(frozen=True)
class FileInfo:
    """What a file holds, which decides the rules that apply to it."""

    path: str
    kind: Kind
    language: str | None
    is_test: bool
    is_generated: bool


def classify(path: str, text: str) -> FileInfo:
    """Decide the kind and the language of one file."""
    repo_path = _without_dist(PurePosixPath(path))
    head = "\n".join(split_lines(text)[:5])
    return FileInfo(
        path=path,
        kind=_kind(repo_path, text),
        language=_language(repo_path, text),
        is_test=bool(TEST_PATH.search(path)),
        is_generated=any(marker in head for marker in GENERATED_MARKERS),
    )


def _without_dist(repo_path: PurePosixPath) -> PurePosixPath:
    """Read a .dist file as the file that it copies, such as phpunit.xml.dist as phpunit.xml."""
    return repo_path.with_suffix("") if repo_path.suffix.lower() == ".dist" else repo_path


def _kind(repo_path: PurePosixPath, text: str) -> Kind:
    suffix = repo_path.suffix.lower()
    if repo_path.name in LOCKFILES or suffix in EXEMPT_EXTENSIONS:
        return "exempt"
    if suffix in CODE_EXTENSIONS or (not suffix and text.startswith("#!")):
        return "code"
    if _is_catalogue(repo_path):
        return "catalogue"
    if suffix in PROSE_EXTENSIONS:
        return "prose"
    if suffix in CONFIG_EXTENSIONS or repo_path.name in CONFIG_NAMES:
        return "config"
    return "other"


def _is_catalogue(repo_path: PurePosixPath) -> bool:
    in_folder = any(part in CATALOGUE_FOLDERS for part in repo_path.parts[:-1])
    android = repo_path.name == "strings.xml" and repo_path.parent.name.startswith("values")
    return in_folder or android or repo_path.suffix.lower() in CATALOGUE_EXTENSIONS


def _language(repo_path: PurePosixPath, text: str) -> str | None:
    if repo_path.suffix:
        return LANGUAGE_BY_EXTENSION.get(repo_path.suffix.lower())
    first_line = split_lines(text)[0]
    if not first_line.startswith("#!"):
        return None
    interpreter = first_line.split()[-1].rsplit("/", 1)[-1]
    return LANGUAGE_BY_INTERPRETER.get(interpreter)


def is_data_json(path: str) -> bool:
    """Tell whether the path is a JSON file in a data or vectors folder, where TELL-1 is off."""
    repo_path = PurePosixPath(path)
    in_folder = any(part in DATA_FOLDERS for part in repo_path.parts[:-1])
    return in_folder and repo_path.suffix.lower() == ".json"
