version = 1

[[annotations]]
path = ["**/*.md", "**/*.json", "**/*.yml", "VERSION", "NOTICE", "templates/NOTICE"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 The Gatepost authors"
SPDX-License-Identifier = "Apache-2.0"
