# SPDX-FileCopyrightText: 2026 The Gatepost authors
# SPDX-License-Identifier: Apache-2.0
"""Tests for check_tells.file_checks: the checks of the name and the lines of a file."""

import unittest

from check_tells import check_text

from tests.check_tells_driver import rules
from tests.check_tells_samples import (
    FIX_ME,
    KIND_BY_PATH,
    LONG_LINE,
    NO_BREAK_SPACE,
    SKIP_MARKER,
    TO_DO,
)

# A line that breaks each rule that a skip comment can skip.
SKIP_SAMPLES = {
    "TELL-1": ("src/a.ts", LONG_LINE),
    "TELL-13": ("src/a.ts", "console.log(x);"),
    "TELL-14": ("src/a.ts", f"const a = '{NO_BREAK_SPACE}';"),
    "CS-6": ("src/a.ts", f"// {TO_DO}: x"),
}


class LineLengthTest(unittest.TestCase):
    def test_accepts_a_line_of_100_characters(self) -> None:
        self.assertEqual(check_text("src/a.ts", "x" * 100), [])

    def test_rejects_a_line_of_101_characters(self) -> None:
        found = check_text("src/a.ts", "x" * 101)
        self.assertEqual(rules(found), ["TELL-1"])
        self.assertEqual(found[0].column, 101)

    def test_counts_a_tab_as_4_columns(self) -> None:
        self.assertEqual(check_text("Makefile", "\t" + "x" * 96), [])
        self.assertEqual(rules(check_text("Makefile", "\t" + "x" * 97)), ["TELL-1"])
        self.assertEqual(check_text("Makefile", "\t\t" + "x" * 92), [])
        self.assertEqual(rules(check_text("Makefile", "\t\t" + "x" * 93)), ["TELL-1"])

    def test_skips_a_line_with_a_url(self) -> None:
        for scheme in ("https", "http"):
            with self.subTest(scheme=scheme):
                line = f"// {scheme}://example.com/" + "a" * 100
                self.assertEqual(check_text("src/a.ts", line), [])

    def test_skips_markdown_lockfiles_and_vectors(self) -> None:
        self.assertEqual(check_text("README.md", "word " * 40), [])
        self.assertEqual(check_text("pnpm-lock.yaml", "x" * 150), [])
        self.assertEqual(check_text("vectors/parse.json", "x" * 150), [])

    def test_skips_json_in_a_data_folder(self) -> None:
        self.assertEqual(check_text("data/states.json", "x" * 150), [])
        self.assertEqual(check_text("vectors/parse.json", "x" * 150), [])
        self.assertEqual(check_text("spec/vectors/parse.json", "x" * 150), [])
        self.assertEqual(check_text("spec/data/format.json", "x" * 150), [])

    def test_checks_other_files_in_a_data_folder(self) -> None:
        self.assertEqual(rules(check_text("data/rules.yml", "x" * 150)), ["TELL-1"])
        self.assertEqual(rules(check_text("vectors/build.py", "x" * 150)), ["TELL-1"])
        self.assertEqual(rules(check_text("package.json", "x" * 150)), ["TELL-1"])
        self.assertEqual(rules(check_text("database/rules.json", "x" * 150)), ["TELL-1"])

    def test_skips_a_message_catalogue(self) -> None:
        line = '{"title": "' + "x" * 150 + '"}'
        self.assertEqual(check_text("src/locales/en.json", line), [])

    def test_skips_a_generated_file(self) -> None:
        text = "// @generated by a script\n" + "x" * 150
        self.assertEqual(check_text("src/spec-data.ts", text), [])

    def test_skips_files_that_other_tools_generate(self) -> None:
        cases = {
            "src/A.cs": "// <auto-generated/>\n",
            "lib/a.g.dart": "// GENERATED CODE - DO NOT MODIFY BY HAND\n",
        }
        for path, header in cases.items():
            with self.subTest(path=path):
                self.assertEqual(check_text(path, header + "x" * 150), [])

    def test_honours_a_skip_with_a_reason(self) -> None:
        line = "x" * 120 + "  // check-tells: allow TELL-1 because the regex cannot be split"
        self.assertEqual(check_text("src/a.ts", line), [])

    def test_checks_each_code_and_config_kind(self) -> None:
        for kind in ("code", "config"):
            for path in KIND_BY_PATH[kind]:
                with self.subTest(path=path):
                    self.assertEqual(rules(check_text(path, LONG_LINE)), ["TELL-1"])

    def test_leaves_every_other_kind_alone(self) -> None:
        for kind in ("prose", "catalogue", "exempt", "other"):
            for path in KIND_BY_PATH[kind]:
                with self.subTest(path=path):
                    self.assertEqual(check_text(path, LONG_LINE), [])

    def test_reads_a_marker_in_the_first_5_lines_of_a_file(self) -> None:
        for marker in ("@generated", "DO NOT EDIT", "<auto-generated", "GENERATED CODE"):
            for marker_line in (1, 5):
                with self.subTest(marker=marker, line=marker_line):
                    text = "\n" * (marker_line - 1) + f"// {marker}\n{LONG_LINE}"
                    self.assertEqual(check_text("src/a.ts", text), [])

    def test_ignores_a_marker_after_the_first_5_lines(self) -> None:
        for marker in ("@generated", "DO NOT EDIT", "<auto-generated", "GENERATED CODE"):
            with self.subTest(marker=marker):
                text = "\n" * 5 + f"// {marker}\n{LONG_LINE}"
                found = check_text("src/a.ts", text)
                self.assertEqual([(v.rule, v.line) for v in found], [("TELL-1", 7)])

    def test_checks_the_other_rules_in_a_generated_file(self) -> None:
        text = "// @generated\nconsole.log(1);\n// " + TO_DO + ": x"
        self.assertEqual(rules(check_text("src/a.ts", text)), ["TELL-13", "CS-6"])


class FileNameTest(unittest.TestCase):
    def test_rejects_utils_helpers_common_and_misc(self) -> None:
        for name in ("src/utils.ts", "lib/helpers.py", "common.go", "pkg/Misc.kt"):
            with self.subTest(name=name):
                self.assertEqual(rules(check_text(name, "")), ["TELL-7"])

    def test_rejects_the_name_with_any_extension_or_none(self) -> None:
        for name in ("utils", "helpers.test.ts", "common.d.ts", "src/MISC.md", "Utils.json"):
            with self.subTest(name=name):
                self.assertEqual(rules(check_text(name, "")), ["TELL-7"])

    def test_accepts_a_folder_named_common(self) -> None:
        self.assertEqual(check_text("common/parse.ts", ""), [])

    def test_accepts_a_name_that_only_starts_with_one_of_the_words(self) -> None:
        self.assertEqual(check_text("src/utilities.ts", ""), [])
        self.assertEqual(check_text("src/commonly.ts", ""), [])


class TodoFormTest(unittest.TestCase):
    def test_rejects_a_to_do_without_an_issue(self) -> None:
        self.assertEqual(rules(check_text("src/a.ts", f"// {TO_DO}: handle 00")), ["CS-6"])

    def test_rejects_a_to_do_in_a_config_file(self) -> None:
        found = check_text("Makefile", "# " + TO_DO + ": pin the version")
        self.assertEqual(rules(found), ["CS-6"])

    def test_rejects_a_to_do_or_a_fix_me_in_any_letter_case(self) -> None:
        for word in (TO_DO, TO_DO.lower(), TO_DO.title(), FIX_ME, FIX_ME.lower(), FIX_ME.title()):
            with self.subTest(word=word):
                found = check_text("src/a.ts", f"// {word}: handle 00")
                self.assertEqual(rules(found), ["CS-6"])
                self.assertEqual(found[0].column, 4)
                self.assertEqual(
                    found[0].message, f"Link an issue in the form {word.upper()}(#123)."
                )

    def test_accepts_a_to_do_with_an_issue(self) -> None:
        self.assertEqual(check_text("src/a.ts", f"// {TO_DO}(#12): handle 00"), [])

    def test_accepts_a_to_do_or_a_fix_me_with_an_issue_in_any_letter_case(self) -> None:
        for word in (TO_DO, TO_DO.lower(), FIX_ME, FIX_ME.title()):
            with self.subTest(word=word):
                self.assertEqual(check_text("src/a.ts", f"// {word}(#12): handle 00"), [])

    def test_rejects_a_to_do_with_a_bad_issue_reference(self) -> None:
        for reference in ("(12)", "(#)", "(#x)", " (#12)"):
            with self.subTest(reference=reference):
                found = check_text("src/a.ts", f"// {TO_DO}{reference}: handle 00")
                self.assertEqual(rules(found), ["CS-6"])

    def test_accepts_a_word_that_only_contains_to_do(self) -> None:
        line = "const todos = 1; const mastodon = 2; const fixmeLater = 3; // _todo_form"
        self.assertEqual(check_text("src/a.ts", line), [])

    def test_ignores_prose(self) -> None:
        self.assertEqual(check_text("docs/notes.md", f"{TO_DO}: write this"), [])

    def test_checks_a_config_file_that_php_tools_use(self) -> None:
        found = check_text("phpstan.dist.neon", "# " + TO_DO + ": raise the level")
        self.assertEqual(rules(found), ["CS-6"])


class SkipTest(unittest.TestCase):
    def test_rejects_a_skip_without_a_reason(self) -> None:
        line = "x" * 120 + f"  // {SKIP_MARKER} TELL-1"
        self.assertEqual(sorted(rules(check_text("src/a.ts", line))), ["SKIP", "TELL-1"])

    def test_rejects_a_skip_of_a_rule_that_cannot_be_skipped(self) -> None:
        line = f"const a = 1; // {SKIP_MARKER} TELL-7 because it is short"
        self.assertEqual(rules(check_text("src/a.ts", line)), ["SKIP"])

    def test_skips_each_rule_that_a_skip_comment_can_skip(self) -> None:
        for rule, (path, line) in SKIP_SAMPLES.items():
            with self.subTest(rule=rule):
                self.assertEqual(rules(check_text(path, line)), [rule])
                skipped = f"{line}  // {SKIP_MARKER} {rule} because the line is a sample"
                self.assertEqual(check_text(path, skipped), [])

    def test_rejects_a_skip_of_each_rule_that_cannot_be_skipped(self) -> None:
        for rule in ("TELL-2", "TELL-7", "TELL-18", "CS-5", "API-3", "GIT-1"):
            with self.subTest(rule=rule):
                line = f"const a = 1; // {SKIP_MARKER} {rule} because it is short"
                found = check_text("src/a.ts", line)
                self.assertEqual(rules(found), ["SKIP"])
                self.assertEqual(found[0].column, 17)

    def test_skips_only_the_rule_that_the_comment_names(self) -> None:
        line = f"console.log('{LONG_LINE}');  // {SKIP_MARKER} TELL-1 because the string is data"
        self.assertEqual(rules(check_text("src/a.ts", line)), ["TELL-13"])

    def test_skips_only_the_line_that_holds_the_comment(self) -> None:
        text = f"console.log(1); // {SKIP_MARKER} TELL-13 because it is a sample\nconsole.log(2);"
        found = check_text("src/a.ts", text)
        self.assertEqual([(v.rule, v.line) for v in found], [("TELL-13", 2)])

    def test_honours_a_skip_in_a_config_file(self) -> None:
        line = f"{LONG_LINE}  # {SKIP_MARKER} TELL-1 because the value is a hash"
        self.assertEqual(check_text("Makefile", line), [])

    def test_ignores_a_skip_marker_in_prose(self) -> None:
        line = "A line such as `" + SKIP_MARKER + " TELL-1` has no reason."
        self.assertEqual(check_text("README.md", line), [])
