# SPDX-FileCopyrightText: 2026 The Gatepost authors
# SPDX-License-Identifier: Apache-2.0
"""Tests for check_tells."""

import contextlib
import io
import subprocess
import tempfile
import unittest
from pathlib import Path

import check_tells
from check_tells import Violation, check_commit_message, check_text

EMOJI = chr(0x1F600)
NO_BREAK_SPACE = chr(0x00A0)
E_ACUTE = chr(0x00E9)
EM_DASH = chr(0x2014)
LINE_SEPARATOR = chr(0x2028)
# Built from two parts, so that this file passes its own to-do check.
TO_DO = "TO" + "DO"
# Built from two parts, so that this file passes its own skip check.
SKIP_MARKER = "check-tells: " + "allow"


def rules(violations: list[Violation]) -> list[str]:
    return [violation.rule for violation in violations]


class LineLengthTest(unittest.TestCase):
    def test_accepts_a_line_of_100_characters(self) -> None:
        self.assertEqual(check_text("src/a.ts", "x" * 100), [])

    def test_rejects_a_line_of_101_characters(self) -> None:
        found = check_text("src/a.ts", "x" * 101)
        self.assertEqual(rules(found), ["TELL-1"])
        self.assertEqual(found[0].column, 101)

    def test_counts_a_tab_as_4_columns(self) -> None:
        self.assertEqual(rules(check_text("Makefile", "\t" + "x" * 97)), ["TELL-1"])

    def test_skips_a_line_with_a_url(self) -> None:
        self.assertEqual(check_text("src/a.ts", "// https://example.com/" + "a" * 100), [])

    def test_skips_markdown_lockfiles_and_vectors(self) -> None:
        self.assertEqual(check_text("README.md", "word " * 40), [])
        self.assertEqual(check_text("pnpm-lock.yaml", "x" * 150), [])
        self.assertEqual(check_text("vectors/parse.json", "x" * 150), [])

    def test_skips_json_in_a_data_folder(self) -> None:
        self.assertEqual(check_text("data/states.json", "x" * 150), [])
        self.assertEqual(check_text("spec/vectors/parse.json", "x" * 150), [])

    def test_checks_other_files_in_a_data_folder(self) -> None:
        self.assertEqual(rules(check_text("data/rules.yml", "x" * 150)), ["TELL-1"])
        self.assertEqual(rules(check_text("vectors/build.py", "x" * 150)), ["TELL-1"])
        self.assertEqual(rules(check_text("package.json", "x" * 150)), ["TELL-1"])

    def test_skips_a_message_catalogue(self) -> None:
        line = '{"title": "' + "x" * 150 + '"}'
        self.assertEqual(check_text("src/locales/en.json", line), [])

    def test_skips_a_generated_file(self) -> None:
        text = "// @generated by a script\n" + "x" * 150
        self.assertEqual(check_text("src/spec-data.ts", text), [])

    def test_skips_files_that_other_tools_generate(self) -> None:
        cases = {
            "src/A.cs": "// <auto-generated/>\n",
            "lib/a.g.dart": "// GENERATED CODE - DO NOT MODIFY BY HAND\n",
        }
        for path, header in cases.items():
            with self.subTest(path=path):
                self.assertEqual(check_text(path, header + "x" * 150), [])

    def test_honours_a_skip_with_a_reason(self) -> None:
        line = "x" * 120 + "  // check-tells: allow TELL-1 because the regex cannot be split"
        self.assertEqual(check_text("src/a.ts", line), [])


class FileNameTest(unittest.TestCase):
    def test_rejects_utils_helpers_common_and_misc(self) -> None:
        for name in ("src/utils.ts", "lib/helpers.py", "common.go", "pkg/Misc.kt"):
            with self.subTest(name=name):
                self.assertEqual(rules(check_text(name, "")), ["TELL-7"])

    def test_accepts_a_folder_named_common(self) -> None:
        self.assertEqual(check_text("common/parse.ts", ""), [])


class TodoFormTest(unittest.TestCase):
    def test_rejects_a_to_do_without_an_issue(self) -> None:
        self.assertEqual(rules(check_text("src/a.ts", f"// {TO_DO}: handle 00")), ["CS-6"])

    def test_rejects_a_to_do_in_a_config_file(self) -> None:
        found = check_text("Makefile", "# " + TO_DO + ": pin the version")
        self.assertEqual(rules(found), ["CS-6"])

    def test_accepts_a_to_do_with_an_issue(self) -> None:
        self.assertEqual(check_text("src/a.ts", f"// {TO_DO}(#12): handle 00"), [])

    def test_ignores_prose(self) -> None:
        self.assertEqual(check_text("docs/notes.md", f"{TO_DO}: write this"), [])


class DebugCallTest(unittest.TestCase):
    def test_rejects_a_debug_call_in_each_language(self) -> None:
        cases = {
            "src/a.ts": "console.log(code);",
            "src/b.ts": "debugger;",
            "src/a.php": "var_dump($code);",
            "pkg/a.py": "print(code)",
            "pkg/b.py": "pdb.set_trace()",
            "pkg/c.py": "breakpoint()",
            "a.go": "fmt.Println(code)",
            "b.go": 'log.Printf("x")',
            "src/A.kt": "println(code)",
            "src/B.kt": 'Log.d(TAG, "x")',
            "src/A.java": "System.out.println(x);",
            "src/B.java": "e.printStackTrace();",
            "src/A.cs": "Console.WriteLine(code);",
            "lib/a.dart": "debugPrint(code);",
            "Sources/A.swift": "dump(code)",
            "Sources/B.swift": 'NSLog("x")',
        }
        for path, line in cases.items():
            with self.subTest(path=path):
                self.assertEqual(rules(check_text(path, line)), ["TELL-13"])

    def test_checks_a_code_file_in_a_catalogue_folder(self) -> None:
        found = check_text("src/messages/format.ts", "console.log(1);")
        self.assertEqual(rules(found), ["TELL-13"])

    def test_accepts_methods_with_similar_names(self) -> None:
        self.assertEqual(check_text("pkg/a.py", "report.print(code)"), [])
        self.assertEqual(check_text("pkg/a.py", "pprint_table(code)"), [])

    def test_ignores_test_files_and_comment_lines(self) -> None:
        self.assertEqual(check_text("example_test.go", 'fmt.Println("EK-01")'), [])
        self.assertEqual(check_text("src/a.ts", " * console.log(parse(code));"), [])

    def test_ignores_each_kind_of_test_path(self) -> None:
        cases = {
            "test/parse.ts": "console.log(code);",
            "src/__tests__/parse.ts": "console.log(code);",
            "lib/parse_test.dart": "debugPrint(code);",
            "src/parse.test.ts": "console.log(code);",
            "src/parse.spec.mjs": "console.log(code);",
            "test_parse.py": "print(code)",
            "src/ParseTest.kt": "println(code)",
            "Sources/ParseTests.swift": "dump(code)",
        }
        for path, line in cases.items():
            with self.subTest(path=path):
                self.assertEqual(check_text(path, line), [])

    def test_ignores_each_kind_of_comment_start(self) -> None:
        cases = [
            ("src/a.ts", "// console.log(x)"),
            ("src/a.ts", "/* console.log(x)"),
            ("src/a.ts", " * console.log(x)"),
            ("pkg/a.py", "# print(x)"),
        ]
        for path, line in cases:
            with self.subTest(line=line):
                self.assertEqual(check_text(path, line), [])

    def test_ignores_doctest_examples(self) -> None:
        self.assertEqual(check_text("pkg/a.py", '    >>> print(parse("EK01A03FK01"))'), [])
        self.assertEqual(check_text("pkg/a.py", "    ...     print(code)"), [])

    def test_checks_a_spread_line_outside_python(self) -> None:
        line = "    ...items.map((item) => console.log(item)),"
        self.assertEqual(rules(check_text("src/a.ts", line)), ["TELL-13"])

    def test_reads_the_language_from_a_shebang(self) -> None:
        self.assertEqual(
            rules(check_text("scripts/run", "#!/usr/bin/env python3\nprint(1)")), ["TELL-13"]
        )


class CharacterTest(unittest.TestCase):
    def test_rejects_an_emoji_in_markdown(self) -> None:
        self.assertEqual(rules(check_text("README.md", f"Done {EMOJI}")), ["TELL-14"])

    def test_rejects_an_hourglass_in_markdown(self) -> None:
        self.assertEqual(rules(check_text("README.md", "Waiting " + chr(0x23F3))), ["TELL-14"])
        self.assertEqual(rules(check_text("README.md", "Done " + chr(0x231B))), ["TELL-14"])

    def test_rejects_non_ascii_in_code(self) -> None:
        found = check_text("src/a.ts", f"const space = '{NO_BREAK_SPACE}';")
        self.assertEqual(rules(found), ["TELL-14"])
        self.assertIn("U+00A0", found[0].message)

    def test_accepts_non_ascii_in_prose_and_catalogues(self) -> None:
        self.assertEqual(check_text("docs/guide.md", f"Caf{E_ACUTE}"), [])
        self.assertEqual(check_text("src/locales/yo.json", f'{{"title": "Caf{E_ACUTE}"}}'), [])

    def test_rejects_an_emoji_in_a_catalogue(self) -> None:
        found = check_text("src/locales/en.json", f'{{"ok": "{EMOJI}"}}')
        self.assertEqual(rules(found), ["TELL-14"])


class LineSplitTest(unittest.TestCase):
    def test_keeps_a_line_separator_inside_the_line(self) -> None:
        text = "const a = 1;" + LINE_SEPARATOR + "const b = 2;"
        self.assertEqual(rules(check_text("src/a.ts", text)), ["TELL-14"])

    def test_keeps_the_line_numbers_after_a_form_feed(self) -> None:
        found = check_text("src/a.ts", "const a = 1;" + chr(0x0C) + "\nconsole.log(1);")
        self.assertEqual(rules(found), ["TELL-13"])
        self.assertEqual(found[0].line, 2)

    def test_treats_crlf_like_lf(self) -> None:
        text = "x" * 100 + "\nconsole.log(1);\n"
        found = check_text("src/a.ts", text.replace("\n", "\r\n"))
        self.assertEqual(rules(found), ["TELL-13"])
        self.assertEqual(found, check_text("src/a.ts", text))


class SkipTest(unittest.TestCase):
    def test_rejects_a_skip_without_a_reason(self) -> None:
        line = "x" * 120 + f"  // {SKIP_MARKER} TELL-1"
        self.assertEqual(sorted(rules(check_text("src/a.ts", line))), ["SKIP", "TELL-1"])

    def test_rejects_a_skip_of_a_rule_that_cannot_be_skipped(self) -> None:
        line = f"const a = 1; // {SKIP_MARKER} TELL-7 because it is short"
        self.assertEqual(rules(check_text("src/a.ts", line)), ["SKIP"])

    def test_ignores_a_skip_marker_in_prose(self) -> None:
        line = "A line such as `" + SKIP_MARKER + " TELL-1` has no reason."
        self.assertEqual(check_text("README.md", line), [])


class CommitMessageTest(unittest.TestCase):
    def test_accepts_a_good_message(self) -> None:
        message = "fix(core): reject a unit of 00\n\nThe spec forbids 00.\n"
        self.assertEqual(check_commit_message(message), [])

    def test_rejects_a_long_subject(self) -> None:
        self.assertEqual(rules(check_commit_message("fix: " + "a" * 70)), ["TELL-18"])

    def test_rejects_an_emoji(self) -> None:
        self.assertEqual(rules(check_commit_message(f"fix: parse codes {EMOJI}")), ["TELL-14"])

    def test_accepts_an_accented_name_in_a_sign_off(self) -> None:
        message = f"fix: parse codes\n\nSigned-off-by: Ad{E_ACUTE} Bello <a@example.com>\n"
        self.assertEqual(check_commit_message(message), [])

    def test_ignores_git_comment_lines(self) -> None:
        self.assertEqual(check_commit_message(f"fix: parse codes\n# {EMOJI} from git\n"), [])

    def test_rejects_non_ascii_in_a_subject(self) -> None:
        self.assertEqual(rules(check_commit_message("fix: parse caf" + E_ACUTE)), ["TELL-14"])

    def test_rejects_non_ascii_in_a_body_but_not_in_a_sign_off(self) -> None:
        message = (
            "fix: parse codes\n\n"
            f"Use a dash {EM_DASH} here.\n\n"
            f"Signed-off-by: Ad{E_ACUTE} Bello <a@example.com>\n"
        )
        found = check_commit_message(message)
        self.assertEqual(rules(found), ["TELL-14"])
        self.assertEqual(found[0].line, 3)

    def test_reads_a_sign_off_without_regard_to_case(self) -> None:
        message = f"fix: parse codes\n\nCo-Authored-By: Ad{E_ACUTE} Bello <a@example.com>"
        self.assertEqual(check_commit_message(message), [])

    def test_stops_at_the_scissors_line(self) -> None:
        scissors = "# ------------------------ >8 ------------------------"
        message = f"fix: parse codes\n{scissors}\n+    caf{E_ACUTE}"
        self.assertEqual(check_commit_message(message), [])

    def test_reports_the_real_line_of_a_character(self) -> None:
        found = check_commit_message(f"# c1\n# c2\nfix: caf{E_ACUTE}")
        self.assertEqual(rules(found), ["TELL-14"])
        self.assertEqual(found[0].line, 3)

    def test_reports_the_real_line_of_a_long_subject(self) -> None:
        found = check_commit_message("# note\nfix: " + "a" * 70)
        self.assertEqual(rules(found), ["TELL-18"])
        self.assertEqual(found[0].line, 2)


class CommandTest(unittest.TestCase):
    def test_checks_new_files_and_skips_ignored_ones(self) -> None:
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            subprocess.run(["git", "init", "-q", str(root)], check=True)
            (root / ".gitignore").write_text("ignored.ts\n", encoding="utf-8")
            (root / "ignored.ts").write_text("console.log(1);\n", encoding="utf-8")
            (root / "new.ts").write_text("console.log(1);\n", encoding="utf-8")
            output = io.StringIO()
            with contextlib.redirect_stdout(output):
                status = check_tells.main(["--root", str(root)])
            self.assertEqual(status, 1)
            self.assertIn("new.ts:1:1: TELL-13", output.getvalue())
            self.assertNotIn("ignored.ts", output.getvalue())

    def test_exits_with_0_for_a_clean_repo(self) -> None:
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            subprocess.run(["git", "init", "-q", str(root)], check=True)
            (root / "clean.ts").write_text("export const a = 1;\n", encoding="utf-8")
            command = [str(Path(__file__).resolve().parents[1] / "check-tells"), "--root", folder]
            self.assertEqual(subprocess.run(command, check=False).returncode, 0)
