# SPDX-FileCopyrightText: 2026 The Gatepost authors
# SPDX-License-Identifier: Apache-2.0
"""Find the agent tells that language tools miss.

The rules come from standards/CODING_STANDARDS.md: TELL-1, TELL-7, TELL-13, TELL-14
and TELL-18, and CS-6 for the form of to-do comments. For the message that a squash merge
puts on main, it also checks GIT-1 and GIT-2.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Literal

# Code and config files get the strict rules. The other kinds can use any script, so they get
# only the emoji check: prose (Markdown), catalogue (translations), exempt (lockfiles, data and
# images) and other (a file type that no rule names).
Kind = Literal["code", "config", "prose", "catalogue", "exempt", "other"]
NumberedLine = tuple[int, str]

MAX_LINE = 100
TAB_WIDTH = 4
MAX_SUBJECT = 72
LAST_ASCII = 0x7F
EXIT_BAD_INPUT = 2
GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "<auto-generated", "GENERATED CODE")
# In lower case, because git reads the keys of trailer lines without regard to case.
SIGN_OFF_PREFIXES = ("signed-off-by:", "co-authored-by:")
COMMIT_TYPES = (
    "build",
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "revert",
    "style",
    "test",
)
COMMIT_TYPE_LIST = f"{', '.join(COMMIT_TYPES[:-1])} or {COMMIT_TYPES[-1]}"

CODE_EXTENSIONS = frozenset(
    {
        ".ts",
        ".tsx",
        ".mts",
        ".cts",
        ".js",
        ".jsx",
        ".mjs",
        ".cjs",
        ".php",
        ".py",
        ".go",
        ".kt",
        ".kts",
        ".java",
        ".cs",
        ".dart",
        ".swift",
        ".sql",
        ".sh",
        ".bash",
        ".css",
        ".scss",
        ".html",
        ".astro",
        ".vue",
        ".svelte",
    }
)
CONFIG_EXTENSIONS = frozenset(
    {
        ".json",
        ".yml",
        ".yaml",
        ".toml",
        ".xml",
        ".ini",
        ".cfg",
        ".properties",
        ".gradle",
        ".neon",
        ".json5",
        ".jsonc",
    }
)
CONFIG_NAMES = frozenset(
    {"Makefile", "Dockerfile", ".editorconfig", ".gitignore", ".gitattributes", ".npmrc"}
)
PROSE_EXTENSIONS = frozenset({".md", ".mdx"})
EXEMPT_EXTENSIONS = frozenset(
    {".svg", ".lock", ".csv", ".txt", ".api", ".snap", ".png", ".jpg", ".ico"}
)
# A lockfile with the suffix .lock is exempt through EXEMPT_EXTENSIONS, so this names the others.
LOCKFILES = frozenset(
    {
        "pnpm-lock.yaml",
        "package-lock.json",
        "go.sum",
        "Package.resolved",
        "gradle.lockfile",
        "packages.lock.json",
    }
)
CATALOGUE_FOLDERS = frozenset({"locales", "i18n", "l10n", "messages"})
DATA_FOLDERS = frozenset({"data", "vectors"})
CATALOGUE_EXTENSIONS = frozenset({".arb", ".po", ".xlf", ".xliff", ".strings", ".stringsdict"})
FORBIDDEN_STEMS = frozenset({"utils", "helpers", "common", "misc"})
SKIPPABLE_RULES = frozenset({"TELL-1", "TELL-13", "TELL-14", "CS-6"})

LANGUAGE_BY_EXTENSION = {
    ".ts": "javascript",
    ".tsx": "javascript",
    ".mts": "javascript",
    ".cts": "javascript",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".astro": "javascript",
    ".vue": "javascript",
    ".svelte": "javascript",
    ".php": "php",
    ".py": "python",
    ".go": "go",
    ".kt": "jvm",
    ".kts": "jvm",
    ".java": "jvm",
    ".cs": "dotnet",
    ".dart": "dart",
    ".swift": "swift",
}
LANGUAGE_BY_INTERPRETER = {"python3": "python", "python": "python", "node": "javascript"}

DEBUG_CALLS: dict[str, tuple[re.Pattern[str], ...]] = {
    "javascript": (re.compile(r"\bconsole\.(log|debug|dir)\s*\("), re.compile(r"\bdebugger\b")),
    "php": (
        re.compile(
            r"(?<![\w>$:])(var_dump|print_r|var_export|dd|dump|error_log|debug_print_backtrace)"
            r"\s*\("
        ),
    ),
    "python": (
        re.compile(r"(?<![\w.])(print|pprint|breakpoint)\s*\("),
        re.compile(r"\bpdb\.set_trace\s*\("),
    ),
    "go": (
        re.compile(r"\bfmt\.Print(f|ln)?\s*\("),
        re.compile(r"\blog\.(Print|Fatal|Panic)(f|ln)?\s*\("),
        re.compile(r"(?<![\w.])(print|println)\s*\("),
    ),
    "jvm": (
        re.compile(r"(?<![\w.])(print|println)\s*\("),
        re.compile(r"\bSystem\.(out|err)\b"),
        re.compile(r"\.printStackTrace\s*\("),
        re.compile(r"\bLog\.(v|d|i|w|e|wtf)\s*\("),
    ),
    "dotnet": (re.compile(r"\b(Console|Debug|Trace)\.Write(Line)?\s*\("),),
    "dart": (re.compile(r"(?<![\w.])(print|debugPrint)\s*\("),),
    "swift": (re.compile(r"(?<![\w.])(print|dump|debugPrint|NSLog)\s*\("),),
}

TEST_PATH = re.compile(
    r"(^|/)(test|tests|__tests__|testdata|Tests)/"
    r"|_test\.(go|dart)$"
    r"|\.(test|spec)\.[cm]?[jt]sx?$"
    r"|(^|/)test_[^/]*\.py$"
    r"|Tests?\.(kt|java|cs|swift)$"
)
COMMENT_LINE = re.compile(r"^\s*(//|/\*|\*|#)")
# Doctest prompts (>>> and ...) start the examples in Python docstrings.
DOCTEST_LINE = re.compile(r"^\s*(>>>|\.\.\.)")
URL = re.compile(r"https?://")
# The words are split, so that this line does not match its own pattern.
TODO_FORM = re.compile(r"\b(?:TO" r"DO|FIX" r"ME)\b(?!\(#\d+\))", re.IGNORECASE)
SKIP = re.compile(r"check-tells: allow ([A-Z]+-\d+)(?: because (\S.*))?")
# A type, a scope that can be missing, a mark for a breaking change that can be missing, a colon,
# a space and text.
SUBJECT_FORM = re.compile(r"(?P<type>[a-z]+)(?P<scope>\([^()\s]+\))?!?: \S")
SIGN_OFF = re.compile(r"signed-off-by:[ \t]+[^<>\s][^<>]*<[^<>\s]+@[^<>\s]+>[ \t]*", re.IGNORECASE)
# The address in the sign-off line of templates/PULL_REQUEST_TEMPLATE.md.
PLACEHOLDER_ADDRESS = "you@example.com"
# The start of the paragraph in that template that asks the author for prose.
TEMPLATE_PARAGRAPH = "Write two or three sentences of plain prose"
EMPTY_CLOSES_LINE = re.compile(r"closes #\s*", re.IGNORECASE)
HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
SQUASH_NOTE = " The subject is the title plus the ' (#N)' that the squash merge adds."
EMOJI_RANGES = (
    (0x1F000, 0x1FAFF),
    (0x231A, 0x231B),
    (0x23E9, 0x23F3),
    (0x2600, 0x27BF),
    (0x2B00, 0x2BFF),
    (0xFE0F, 0xFE0F),
)


@dataclass(frozen=True, order=True)
class Violation:
    """One broken rule at one place in a file."""

    path: str
    line: int
    column: int
    rule: str
    message: str

    def __str__(self) -> str:
        """Format the violation like a compiler message."""
        return f"{self.path}:{self.line}:{self.column}: {self.rule} {self.message}"


class InputError(Exception):
    """The command line names something that check-tells cannot read."""


@dataclass(frozen=True)
class FileInfo:
    """What a file holds, which decides the rules that apply to it."""

    path: str
    kind: Kind
    language: str | None
    is_test: bool
    is_generated: bool


def _split_lines(text: str) -> list[str]:
    """Split text at line feeds only, and remove one carriage return from each line.

    str.splitlines also splits at U+2028, U+2029, U+0085 and the form feed. That hides the
    characters that TELL-14 looks for, and it moves the line numbers.
    """
    return [line.removesuffix("\r") for line in text.split("\n")]


def classify(path: str, text: str) -> FileInfo:
    """Decide the kind and the language of one file."""
    repo_path = _without_dist(PurePosixPath(path))
    head = "\n".join(_split_lines(text)[:5])
    return FileInfo(
        path=path,
        kind=_kind(repo_path, text),
        language=_language(repo_path, text),
        is_test=bool(TEST_PATH.search(path)),
        is_generated=any(marker in head for marker in GENERATED_MARKERS),
    )


def _without_dist(repo_path: PurePosixPath) -> PurePosixPath:
    """Read a .dist file as the file that it copies, such as phpunit.xml.dist as phpunit.xml."""
    return repo_path.with_suffix("") if repo_path.suffix.lower() == ".dist" else repo_path


def _kind(repo_path: PurePosixPath, text: str) -> Kind:
    suffix = repo_path.suffix.lower()
    if repo_path.name in LOCKFILES or suffix in EXEMPT_EXTENSIONS:
        return "exempt"
    if suffix in CODE_EXTENSIONS or (not suffix and text.startswith("#!")):
        return "code"
    if _is_catalogue(repo_path):
        return "catalogue"
    if suffix in PROSE_EXTENSIONS:
        return "prose"
    if suffix in CONFIG_EXTENSIONS or repo_path.name in CONFIG_NAMES:
        return "config"
    return "other"


def _is_catalogue(repo_path: PurePosixPath) -> bool:
    in_folder = any(part in CATALOGUE_FOLDERS for part in repo_path.parts[:-1])
    android = repo_path.name == "strings.xml" and repo_path.parent.name.startswith("values")
    return in_folder or android or repo_path.suffix.lower() in CATALOGUE_EXTENSIONS


def _language(repo_path: PurePosixPath, text: str) -> str | None:
    if repo_path.suffix:
        return LANGUAGE_BY_EXTENSION.get(repo_path.suffix.lower())
    first_line = _split_lines(text)[0]
    if not first_line.startswith("#!"):
        return None
    interpreter = first_line.split()[-1].rsplit("/", 1)[-1]
    return LANGUAGE_BY_INTERPRETER.get(interpreter)


def _is_emoji(character: str) -> bool:
    return any(low <= ord(character) <= high for low, high in EMOJI_RANGES)


def check_text(path: str, text: str) -> list[Violation]:
    """Check the name and every line of one file."""
    info = classify(path, text)
    violations = _check_name(info)
    for number, line in enumerate(_split_lines(text), start=1):
        violations.extend(_check_line(info, number, line))
    return violations


def _check_name(info: FileInfo) -> list[Violation]:
    stem = PurePosixPath(info.path).name.split(".")[0].lower()
    if stem not in FORBIDDEN_STEMS:
        return []
    message = "Name the file after the concept that it holds, not utils, helpers, common or misc."
    return [Violation(info.path, 1, 1, "TELL-7", message)]


def _check_line(info: FileInfo, number: int, line: str) -> list[Violation]:
    skipped: set[str] = set()
    problems: list[Violation] = []
    if info.kind in ("code", "config"):
        skipped, problems = _skips(info.path, number, line)
    found = [
        violation
        for check in (_line_length, _todo_form, _debug_calls, _characters)
        for violation in check(info, number, line)
        if violation.rule not in skipped
    ]
    return problems + found


def _skips(path: str, number: int, line: str) -> tuple[set[str], list[Violation]]:
    skipped: set[str] = set()
    problems: list[Violation] = []
    for match in SKIP.finditer(line):
        rule, reason = match.group(1), match.group(2)
        if rule in SKIPPABLE_RULES and reason:
            skipped.add(rule)
            continue
        message = (
            f"Skip only {', '.join(sorted(SKIPPABLE_RULES))}, and give a reason after because."
        )
        problems.append(Violation(path, number, match.start() + 1, "SKIP", message))
    return skipped, problems


def _line_length(info: FileInfo, number: int, line: str) -> list[Violation]:
    if info.kind not in ("code", "config") or info.is_generated or _is_data_json(info.path):
        return []
    width = len(line.expandtabs(TAB_WIDTH))
    if width <= MAX_LINE or URL.search(line):
        return []
    message = f"The line is {width} characters wide. Keep lines at {MAX_LINE} or fewer."
    return [Violation(info.path, number, MAX_LINE + 1, "TELL-1", message)]


def _is_data_json(path: str) -> bool:
    repo_path = PurePosixPath(path)
    in_folder = any(part in DATA_FOLDERS for part in repo_path.parts[:-1])
    return in_folder and repo_path.suffix.lower() == ".json"


def _todo_form(info: FileInfo, number: int, line: str) -> list[Violation]:
    if info.kind not in ("code", "config"):
        return []
    return [
        Violation(
            info.path,
            number,
            match.start() + 1,
            "CS-6",
            f"Link an issue in the form {match.group(0).upper()}(#123).",
        )
        for match in TODO_FORM.finditer(line)
    ]


def _is_comment(info: FileInfo, line: str) -> bool:
    if COMMENT_LINE.match(line):
        return True
    return info.language == "python" and bool(DOCTEST_LINE.match(line))


def _debug_calls(info: FileInfo, number: int, line: str) -> list[Violation]:
    if info.kind != "code" or info.is_test or info.language is None or _is_comment(info, line):
        return []
    patterns = DEBUG_CALLS.get(info.language, ())
    return [
        Violation(info.path, number, match.start() + 1, "TELL-13", f"Remove {match.group(0)!r}.")
        for pattern in patterns
        for match in pattern.finditer(line)
    ]


def _characters(info: FileInfo, number: int, line: str) -> list[Violation]:
    found = [
        Violation(info.path, number, index + 1, "TELL-14", f"Remove the emoji U+{ord(char):04X}.")
        for index, char in enumerate(line)
        if _is_emoji(char)
    ]
    if found or info.kind not in ("code", "config"):
        return found
    for index, char in enumerate(line):
        if ord(char) > LAST_ASCII:
            message = f"Write U+{ord(char):04X} as an escape sequence. Code and config use ASCII."
            return [Violation(info.path, number, index + 1, "TELL-14", message)]
    return []


def _message_lines(text: str) -> list[NumberedLine]:
    """Pair each line with its number. Drop git's comment lines, and stop at its scissors line."""
    numbered: list[NumberedLine] = []
    for number, line in enumerate(_split_lines(text), start=1):
        if line.startswith("# ") and ">8" in line:
            break
        if not line.startswith("#"):
            numbered.append((number, line))
    return numbered


def _subject(lines: list[NumberedLine]) -> NumberedLine | None:
    """Find the subject, which is the first line that has text."""
    return next(((number, line) for number, line in lines if line.strip()), None)


def _check_subject(lines: list[NumberedLine], note: str = "") -> list[Violation]:
    """Check the length of the subject. The note adds advice that fits the message."""
    subject = _subject(lines)
    if subject is None or len(subject[1]) <= MAX_SUBJECT:
        return []
    number, text = subject
    message = f"The subject has {len(text)} characters. Use {MAX_SUBJECT} or fewer.{note}"
    return [Violation("commit message", number, MAX_SUBJECT + 1, "TELL-18", message)]


def _first_bad_character(number: int, line: str) -> Violation | None:
    """Find the first emoji, or the first non-ASCII character outside a sign-off line."""
    allow_non_ascii = line.lower().startswith(SIGN_OFF_PREFIXES)
    for index, char in enumerate(line):
        if _is_emoji(char) or (ord(char) > LAST_ASCII and not allow_non_ascii):
            message = f"Remove U+{ord(char):04X}. Commit messages use ASCII."
            return Violation("commit message", number, index + 1, "TELL-14", message)
    return None


def _check_message(lines: list[NumberedLine], note: str = "") -> list[Violation]:
    violations = _check_subject(lines, note)
    for number, line in lines:
        violation = _first_bad_character(number, line)
        if violation is not None:
            violations.append(violation)
    return violations


def _check_subject_form(lines: list[NumberedLine], *, no_scope: bool) -> list[Violation]:
    """Check GIT-1: the subject has a type that Conventional Commits lists, and maybe a scope."""
    subject = _subject(lines)
    if subject is None:
        return [Violation("commit message", 1, 1, "GIT-1", "The message has no subject.")]
    number, text = subject
    match = SUBJECT_FORM.match(text)
    if match is None:
        message = (
            "The subject does not follow Conventional Commits. "
            f"Write 'type: description', where type is {COMMIT_TYPE_LIST}."
        )
        return [Violation("commit message", number, 1, "GIT-1", message)]
    if match["type"] not in COMMIT_TYPES:
        message = f"'{match['type']}' is not a Conventional Commits type. Use {COMMIT_TYPE_LIST}."
        return [Violation("commit message", number, 1, "GIT-1", message)]
    if no_scope and match["scope"]:
        message = (
            f"Remove the scope {match['scope']}. "
            "This repo has no packages, so a subject has no scope."
        )
        column = match.start("scope") + 1
        return [Violation("commit message", number, column, "GIT-1", message)]
    return []


def _check_sign_off(lines: list[NumberedLine], path: str) -> list[Violation]:
    """Check GIT-2: the message has a line 'Signed-off-by: Name <address>', not the template's."""
    sign_offs = [(number, line) for number, line in lines if SIGN_OFF.fullmatch(line)]
    if not sign_offs:
        message = (
            "The message has no Signed-off-by line. Add the line 'Signed-off-by: Name <address>'. "
            "git commit --signoff adds it to a commit, and git rebase --signoff adds it to each "
            "commit of a branch."
        )
        return [Violation(path, 1, 1, "GIT-2", message)]
    message = (
        f"The sign-off still holds the placeholder address {PLACEHOLDER_ADDRESS}. "
        "Write your own name and address."
    )
    return [
        Violation(path, number, 1, "GIT-2", message)
        for number, line in sign_offs
        if PLACEHOLDER_ADDRESS in line.lower()
    ]


def _check_template_text(lines: list[NumberedLine]) -> list[Violation]:
    """Find the text of the pull request template that the author did not replace."""
    violations: list[Violation] = []
    for number, line in lines:
        text = line.strip()
        if text.startswith(TEMPLATE_PARAGRAPH):
            message = (
                "The body still holds the placeholder paragraph of the pull request template. "
                "Replace it with two or three sentences that say what the change does and why."
            )
        elif EMPTY_CLOSES_LINE.fullmatch(text):
            message = (
                "The body still holds the line 'Closes #'. Add the issue number after it. "
                "If the change closes no issue, remove the line."
            )
        else:
            continue
        violations.append(Violation("commit message", number, 1, "TELL-18", message))
    return violations


def check_commit_message(text: str) -> list[Violation]:
    """Check the subject length and the characters of a commit message."""
    return _check_message(_message_lines(text))


def _blank_html_comments(body: str) -> str:
    """Replace each HTML comment with spaces, and keep its line feeds, so that no place moves."""
    return HTML_COMMENT.sub(lambda comment: re.sub(r"[^\n]", " ", comment[0]), body)


def check_squash_message(text: str, *, no_scope: bool = False) -> list[Violation]:
    """Check the message that a squash merge puts on main: the pull request title and body.

    The body is not a git message, so a line that starts with # is text and not a comment. No
    reader sees an HTML comment, and Renovate ends each body with one, so the body check leaves
    them out. The title is the first line, and no comment hides text there.
    """
    subject, line_feed, body = text.partition("\n")
    lines = list(enumerate(_split_lines(subject + line_feed + _blank_html_comments(body)), start=1))
    return [
        *_check_message(lines, SQUASH_NOTE),
        *_check_subject_form(lines, no_scope=no_scope),
        *_check_sign_off(lines, "commit message"),
        *_check_template_text(lines),
    ]


def _git(root: Path, *arguments: str) -> bytes:
    """Run git in root and give its output. A failure is bad input, such as no repo."""
    try:
        run = subprocess.run(["git", "-C", str(root), *arguments], check=True, capture_output=True)
    except subprocess.CalledProcessError as error:
        reason = " ".join(error.stderr.decode(errors="replace").split())
        raise InputError(f"Git failed in {root}: {reason}") from error
    return run.stdout


def tracked_files(root: Path) -> list[Path]:
    """List the files that git tracks, or would track, under root."""
    output = _git(root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
    names = output.decode().split("\0")
    return [root / name for name in names if name and (root / name).is_file()]


def _commits(root: Path, revision_range: str) -> list[tuple[str, str]]:
    """Give the hash and the message of each commit in a range. Merge commits are left out."""
    output = _git(
        root,
        "log",
        "--no-merges",
        "--no-show-signature",
        "--format=%H%n%B%x00",
        "--end-of-options",
        revision_range,
    )
    records = [record.lstrip("\n") for record in output.decode(errors="replace").split("\0")]
    pairs = (record.partition("\n") for record in records if record)
    return [(commit, message) for commit, _, message in pairs]


def check_signed_off(root: Path, revision_range: str) -> list[Violation]:
    """Check that each commit in a revision range has a sign-off. Merge commits are left out."""
    violations: list[Violation] = []
    for commit, message in _commits(root, revision_range):
        lines = list(enumerate(_split_lines(message), start=1))
        violations.extend(_check_sign_off(lines, f"commit {commit[:12]}"))
    return violations


def _read(path: Path) -> bytes:
    try:
        return path.read_bytes()
    except OSError as error:
        raise InputError(f"Cannot read {path}: {error.strerror}.") from error


def _not_utf8(path: str, data: bytes, error: UnicodeDecodeError, advice: str) -> Violation:
    """Point at the first byte that is not UTF-8. All the bytes before it are valid."""
    line_start = data.rfind(b"\n", 0, error.start) + 1
    line = data.count(b"\n", 0, error.start) + 1
    column = len(data[line_start : error.start].decode("utf-8")) + 1
    message = f"Byte 0x{data[error.start]:02X} is not valid UTF-8. {advice}"
    return Violation(path, line, column, "TELL-14", message)


def _check_undecodable(path: str, data: bytes, error: UnicodeDecodeError) -> list[Violation]:
    """Report a code or config file that is not UTF-8. Other files can be binary, so skip them."""
    # Only the suffix and the first bytes decide the kind, and bad bytes would stop the decoder.
    kind = classify(path, data[:512].decode("utf-8", errors="replace")).kind
    if kind not in ("code", "config"):
        return []
    advice = "Save the file as UTF-8, and use ASCII in code and config."
    return [_not_utf8(path, data, error, advice)]


def check_files(root: Path, files: list[Path]) -> list[Violation]:
    """Check each file. Report a code or config file that is not UTF-8, and skip other files."""
    violations: list[Violation] = []
    for file in files:
        if not file.is_relative_to(root):
            raise InputError(f"{file} is outside the root {root}.")
        path = file.relative_to(root).as_posix()
        data = _read(file)
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as error:
            violations.extend(_check_undecodable(path, data, error))
        else:
            violations.extend(check_text(path, text))
    return violations


def _check_message_file(path: Path, check: Callable[[str], list[Violation]]) -> list[Violation]:
    data = _read(path)
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as error:
        advice = "Save the message as UTF-8, and use ASCII."
        return [_not_utf8("commit message", data, error, advice)]
    return check(text)


def _run(args: argparse.Namespace) -> list[Violation]:
    if args.commit_msg is not None:
        return _check_message_file(args.commit_msg, check_commit_message)
    if args.squash_msg is not None:
        return _check_message_file(
            args.squash_msg, lambda text: check_squash_message(text, no_scope=args.no_scope)
        )
    root = args.root.resolve()
    if args.signed_off is not None:
        return check_signed_off(root, args.signed_off)
    files = [(root / path).resolve() for path in args.paths] or tracked_files(root)
    return check_files(root, files)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="check-tells", description="Find the agent tells that language tools miss."
    )
    parser.add_argument("--root", type=Path, default=Path.cwd(), help="The repo root.")
    messages = parser.add_mutually_exclusive_group()
    messages.add_argument(
        "--commit-msg", type=Path, help="Check this commit message file (TELL-14 and TELL-18)."
    )
    messages.add_argument(
        "--squash-msg",
        type=Path,
        help="Check this file as the message that a squash merge puts on main "
        "(TELL-14, TELL-18, GIT-1, GIT-2 and the text of the pull request template).",
    )
    messages.add_argument(
        "--signed-off",
        metavar="RANGE",
        help="Check that each commit in this git revision range has a sign-off (GIT-2).",
    )
    parser.add_argument(
        "--no-scope",
        action="store_true",
        help="With --squash-msg, reject a scope in the subject "
        "(GIT-1 for a repo without packages).",
    )
    parser.add_argument("paths", nargs="*", type=Path, help="Files to check. Default: all.")
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the checks and print each violation.

    Return 0 if all is well, 1 if a rule broke and 2 if the input cannot be read.
    """
    parser = _parser()
    args = parser.parse_args(argv)
    if args.no_scope and args.squash_msg is None:
        parser.error("--no-scope needs --squash-msg.")
    try:
        violations = _run(args)
    except InputError as error:
        sys.stderr.write(f"check-tells: {error}\n")
        return EXIT_BAD_INPUT
    for violation in sorted(violations):
        sys.stdout.write(f"{violation}\n")
    return 1 if violations else 0


if __name__ == "__main__":
    raise SystemExit(main())
